name: 'Terraform Security Scan'
description: "terraform scurity scan"
inputs:
  github_token:
    description: GitHub token to use
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Security scan
      uses: aquasecurity/tfsec-pr-commenter-action@main
      env:
        github_token: ${{ inputs.github_token }}
  security-scan:
    name: Security scan (org-staging)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: TF Security Scan
        uses: triat/terraform-security-scan@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
