name: 'Terraform Security Scan'
description: "terraform scurity scan"
inputs:
  github_token:
    description: GitHub token to use
    required: true
  tf_working_dir:
    description: Path to directory where terraform commands should be run
    required: false
    default: "./"
runs:
  using: "composite"
  steps:
    - name: TF init
      shell: bash
      working-directory: ${{ inputs.tf_working_dir }}
      run: terraform init -input=false -backend=false
    - name: Security scan
      #uses: triat/terraform-security-scan@v3.0.1
      uses: figadore/terraform-security-scan@master
      env:
        github_token: ${{ inputs.github_token }}
      #uses: aquasecurity/tfsec-pr-commenter-action@main
      #with:
      #  github_token: ${{ inputs.github_token }}
